name: Release

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  release:
    uses: AutomationDojo/reusable-cicd/.github/workflows/semantic-release_simple-release.yml@main
    secrets:
      GITHUB_APP_ID: ${{ secrets.DEVOPS_BUDDY_APP_ID }}
      GITHUB_APP_PRIVATE_KEY: ${{ secrets.DEVOPS_BUDDY_PRIVATE_KEY }}
    with:
      extra-plugins: |
        @semantic-release/commit-analyzer
        @semantic-release/release-notes-generator
        @semantic-release/changelog
        @semantic-release/git
        @semantic-release/github